version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: 'weekly'
      day: 'saturday'
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: '@salesforce/dev-scripts'
      - dependency-name: "@salesforce/plugin-*"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
