#!/usr/bin/env bash

# shellcheck disable=SC2034

source ./scripts/_init

function s3upload () {
    maxage="$1"; shift
    local="$1";  shift
    remote="$1"; shift

    # Only allow uploads from the build tmp dir
    if [[ "$local" != "$TMP_DIR"* ]]; then
        stderr "Unexpected upload request from local dir: '$local'"
        exit 1
    fi

    # Only allow uploads to the target s3 bucket
    if [[ "$remote" != "$S3_BASE_UPLOAD_URL"* ]]; then
        stderr "Unexpected upload request to s3 url: '$remote'"
        exit 1
    fi

    extra_args=()
    echo "S3_ENDPOINT: ${S3_ENDPOINT}"
    if [[ ! -z "${S3_ENDPOINT:-}" ]]; then
        extra_args+=("--endpoint-url $S3_ENDPOINT")
    fi

    echo "S3_PROFILE: ${S3_PROFILE}"
    if [[ ! -z "${S3_PROFILE:-}" ]]; then
        extra_args+=("--profile $S3_PROFILE")
    fi

    if [[ "${DEBUG_S3_UPLOAD:-}" == "true" ]]; then
        echo "[SKIP] S3 upload from '$local' to '$remote'..."
        find "$local"
        return 0
    fi

    aws s3 cp ${extra_args[@]+${extra_args[@]}} --cache-control max-age="$maxage" "$local" "$remote" "$@"
}


