#!/usr/bin/env bash

source ./scripts/release/_init

set -ex

script "build/standalone"
script "release/tarballs"

# Generate root manifest with archive entries
createManifest
# Update releases with current version and channel
createReleases
for OS in "${OS_TARGETS[@]}"; do
    setos "$OS"
    IFS='|' read -ra ARCHS <<< "$(archs)"
    for ARCH in "${ARCHS[@]}"; do
        setarch "$ARCH"
        FILE_NAME="${PKG_NAME}-v${VERSION}-${OS}-${ARCH}.tar.xz"
        addToManifest "archives" "${OS}-${ARCH}" "$S3_HOST_CHANNEL_BASE_URL/$FILE_NAME" "$RELEASE_DIR/$FILE_NAME"
        if [[ "$OS" == "linux" ]]; then
            addToManifest "installers" "${OS}-${ARCH}" "$S3_HOST_CHANNEL_BASE_URL/$FILE_NAME" "$RELEASE_DIR/$FILE_NAME"
        fi
    done
done
