#!/usr/bin/env bash

set -ex

source ./scripts/release/_init

CACHE_DIR="$TMP_DIR/s3"
CACHE_VERSION_DIR="$CACHE_DIR/v$VERSION"

rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR"
mkdir -p "$CACHE_VERSION_DIR"
cd "$CACHE_DIR"

for OS in "${OS_TARGETS[@]}"; do
    setos "$OS"
    IFS='|' read -ra ARCHS <<< "$(archs)"
    for ARCH in "${ARCHS[@]}"; do
        setarch "$ARCH"
        mv "$TGZ_PATH" "$VERSIONED_BASE.tar.gz"
        mv "$TXZ_PATH" "$VERSIONED_BASE.tar.xz"
    done
done

s3upload "$VERSIONED_CACHE_CONTROL" \
    --recursive "$CACHE_DIR" \
    "$REMOTE_BASE"

for OS in "${OS_TARGETS[@]}"; do
    setos "$OS"
    IFS='|' read -ra ARCHS <<< "$(archs)"
    for ARCH in "${ARCHS[@]}"; do
        setarch "$ARCH"
        mv "$VERSIONED_BASE.tar.gz" "$UNVERSIONED_BASE.tar.gz"
        mv "$VERSIONED_BASE.tar.xz" "$UNVERSIONED_BASE.tar.xz"
    done
done

s3upload "$UNVERSIONED_CACHE_CONTROL" \
    --recursive "$CACHE_DIR" \
    "$REMOTE_BASE"

rm "$CACHE_DIR"/*

# now upload json files
for OS in "${OS_TARGETS[@]}"; do
    setos "$OS"
    IFS='|' read -ra ARCHS <<< "$(archs)"
    for ARCH in "${ARCHS[@]}"; do
        setarch "$ARCH"
        cp "$RELEASE_DIR/${OS}-${ARCH}" "$CACHE_DIR"
    done
done

# generate version file
cat << EOF > "$RELEASE_DIR/version"
{
    "channel": "${CHANNEL}",
    "version": "${VERSION}"
}
EOF

cp "$RELEASE_DIR/version" "$RELEASE_VERSION_DIR/version"
cp "$RELEASE_DIR/version" "$CACHE_DIR/version"
cp "$RELEASE_DIR/version" "$CACHE_VERSION_DIR/version"
s3upload "$LATEST_VERSION_CACHE_CONTROL" \
    --content-type application/json --recursive "$CACHE_DIR" \
    "$REMOTE_BASE"
