#!/usr/bin/env bash

set -ex

source ./scripts/release/_init

bg script "release/installers/darwin_mobileci"
bg script "release/installers/windows_docker"
wait_all

if [[ "$CHANNEL" == "stable" ]]; then
    script "release/installers/downloads"

    resetS3CacheDir

    cp "$RELEASE_DIR/manifest.json" "$S3_CACHE_DIR"
    s3upload "$LATEST_VERSION_CACHE_CONTROL" \
        "$S3_CACHE_DIR/manifest.json" \
        "$S3_BASE_UPLOAD_URL/" \
        --content-type "application/json"
fi
