#!/usr/bin/env bash

export OS=darwin
export ARCH=x64

source ./scripts/release/_init

set -ex

stdout "Releasing darwin installer to ${CHANNEL}"

s3upload "$UNVERSIONED_CACHE_CONTROL" \
    "${RELEASE_DIR}/$PKG_NAME.pkg" \
    "${S3_CHANNEL_UPLOAD_URL}/$PKG_NAME.pkg"
