#!/usr/bin/env bash

export OS=linux

source ./scripts/release/_init

set +x
echo "$SFDX_DEB_KEY" | base64 -d | gpg --import
set -ex

stdout "Releasing debian installer to ${CHANNEL}"

CACHE_DIR="$TMP_DIR/s3"
DEB_S3_CHANNEL_UPLOAD_URL="s3://$S3_BUCKET/$S3_FOLDER/branches/$CHANNEL/apt"

rm -rf "$CACHE_DIR"
mkdir -p "$CACHE_DIR"
cd "$CACHE_DIR"

# do long cache files first
for ARCH in "${ARCHS[@]}"; do
    setarch "$ARCH"
    mv "$UNVERSIONED_DEB_PATH" "$CACHE_DIR/$VERSIONED_DEB_BASE.deb"
done

s3upload "$VERSIONED_CACHE_CONTROL" \
    "$CACHE_DIR" \
    "$DEB_S3_CHANNEL_UPLOAD_URL" \
    --recursive

# create Package apt file
apt-ftparchive packages . > Packages
gzip -c Packages > Packages.gz
bzip2 -k Packages
xz -k Packages

# create Release apt file
apt-ftparchive -c "$RESOURCES_DIR/deb/apt-ftparchive.conf" release . > Release
gpg --digest-algo SHA512 --clearsign -u 0F1B0520 -o InRelease Release
gpg --digest-algo SHA512 -abs -u 0F1B0520 -o Release.gpg Release

# remove the deb files so we don't push them again
rm ./*.deb

s3upload "$UNVERSIONED_CACHE_CONTROL" \
    "$CACHE_DIR" \
    "$DEB_S3_CHANNEL_UPLOAD_URL" \
    --recursive
