#!/usr/bin/env bash

set -ex

source ./scripts/release/_init

if [[ "${DOCKER_DEBUG:-}" != "true" ]]; then
    set +x
fi

envars=()
passthroughs=(
    "CHANNEL"
    "FORCE_BUILD"
    "http_proxy"
    "HTTP_PROXY"
    "HTTPS_PROXY"
    "NO_PROXY"
    "PARALLEL_OS_BUILDS"
    "DISABLE_YARNCLEAN"
    "SKIP_AWS"
    "WINDOWS_SIGNING_KEY"
    "WINDOWS_SIGNING_PASS"
)

for var in ${passthroughs[@]}; do
    if [[ ! -z "${!var:-}" ]]; then
        envars+=("-e" "$var=${!var}")
    else
        stdout "$var is not defined"
    fi
done

if [[ "${SKIP_AWS:-}" == "true" ]]; then
    stdout "Skipping AWS in docker build"
else
    for var in $(compgen -e); do
        if [[ "$var" == "S3"* ]]; then
            envars+=("-e" "$var=${!var}")
        fi
    done
fi

docker run \
    --rm \
    -v "$ROOT_DIR:/root/sfdx" \
    -w /root/sfdx \
    "${envars[@]}" \
    --entrypoint scripts/release/installers/windows \
    dickeyxxx/cli-engine-docker-nsis:v3.0.3
