#!/usr/bin/env bash

set -ex

source ./scripts/release/_init

set +x

envars=()
if [[ ! -z "${WINDOWS_SIGNING_PASS:-}" ]]; then
    envars+=("-e" "WINDOWS_SIGNING_PASS=$WINDOWS_SIGNING_PASS")
fi
if [[ ! -z "${WINDOWS_SIGNING_KEY:-}" ]]; then
    envars+=("-e" "WINDOWS_SIGNING_KEY=$WINDOWS_SIGNING_KEY")
fi

if [[ ! -z "${SKIP_AWS:-}" ]]; then
    stdout "Skipping AWS in docker build"
    envars+=("-e" "SKIP_AWS=$SKIP_AWS")
else
    for var in $(compgen -e); do
        if [[ "${var}" == "S3"* ]]; then
            envars+=( "-e" "$var=${!var}" )
        fi
    done
fi

docker run \
    --rm \
    -v "$ROOT_DIR:/root/sfdx" \
    -w /root/sfdx \
    "${envars[@]}" \
    --entrypoint scripts/release/installers/windows \
    dickeyxxx/cli-engine-docker-nsis:v3.0.3
