#!/usr/bin/env bash

if [[ "${CHANNEL:-}" != "" ]]; then
    echo "$CHANNEL"
else
    branch="$(git rev-parse --abbrev-ref HEAD)"

    if [[ "$branch" == "master" ]]; then
        echo "stable"
    else
        echo "$USER"
    fi
fi
