#!/usr/bin/env bash

if [[ "${CHANNEL:-}" != "" ]]; then
    echo "$CHANNEL"
else
    branch="$(git rev-parse --abbrev-ref HEAD)"

    if [[ "$branch" == "master" ]]; then
        pjson_channel="$(node -p "try{require('./package.json').cli.channel}catch(e){}")"
        if [[ "$pjson_channel" != "undefined" ]]; then
            echo "$pjson_channel"
        else
            echo "$branch"
        fi
    else
        echo "$USER"
    fi
fi
