#!/usr/bin/env bash

source ./scripts/_init

set -ex

rm -rf \
    "$TMP_DIR" \
    "$RELEASE_DIR"
    # "$ROOT_DIR/node_modules" \ - Move this back to the top of the rm lines if this test doesn't work.
