#!/usr/bin/env bash

source ./scripts/_init

set -x

cd "$BASE_DIR"

# apply yarn clean settings
yarn autoclean --force

# module readmes and other markdown docs not found in template directories
find "$BASE_DIR/node_modules" -name \*.md | grep -v /templates/ | xargs rm

# module test dirs, except in salesforce-alm, which includes production source code in such a dir
find "$BASE_DIR/node_modules" -name test -type d | grep -v /salesforce-alm/ | xargs rm -rf
