#!/usr/bin/env bash

source ./scripts/_init

set -ex

rm -rf \
    "$ROOT_DIR/*.tgz" \
    "$ROOT_DIR/*.sig" \
    "$ROOT_DIR/coverage" \
    "$ROOT_DIR/xunit.xml" \
    "$ROOT_DIR/checkstyle.xml" \
    "$ROOT_DIR/yarn-error.log"
