#!/bin/bash

get_script_dir () {
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [[ -h "$SOURCE" ]]; do
      DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
      SOURCE="$( readlink "$SOURCE" )"
      # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
      [[ "$SOURCE" != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}

get_win_path () {
  echo "$1" | sed -r -e 's,^/mnt,,' -e 's,^/cygdrive,,' -e 's,^/,,' -e 's,/,\\,g' -e 's,^(.),\0:,'
}

DIR=$(get_script_dir)
BIN="$DIR/../client/bin"

SPAWN=$(get_win_path "$DIR/spawn.js")
"$BIN/node.exe" "$SPAWN" "$@"

exit $?
