#!../client/bin/node

const join = require('path').join;
const spawn = require('cross-spawn').sync;
const result = spawn(join(__dirname, 'sfdx.cmd'), process.argv.slice(2), {stdio: 'inherit'});
process.exitCode = result.status;
