#!/usr/bin/env bash

# Archives ship with node_modules, which can include a lot of unused files. Filter all of these out.

set -ex

function filter() {
  (grep -v "$1" || true)
}

# Remove JSforceTestSuite from dist
find node_modules -name 'JSforceTestSuite' -type d \
  | filter '/templates/' \
  | xargs rm -rf

# Module readmes and other markdown docs and config not found in template directories
find node_modules -name '*.md' -type f \
  | filter '/templates/' \
  | xargs rm -f
find node_modules -name '.gitignore' -type f \
  | filter '/templates/' \
  | xargs ls -l
find node_modules -name '.eslintrc' -type f \
  | filter '/templates/' \
  | xargs rm -f
find node_modules -name '.gitattributes' -type f \
  | filter '/templates/' \
  | xargs rm -f
find node_modules -name 'appveyor.yml' -type f \
  | filter '/templates/' \
  | xargs rm -f
find node_modules -name 'circle.yml' -type f \
  | filter '/templates/' \
  | xargs rm -f

# Module test dirs, except in salesforce-alm, which includes production source code in such a dir
find node_modules -name 'test' -type d \
  | filter '/command/' \
  | filter '/commands/' \
  | filter '/lib/' \
  | filter '/dist/' \
  | filter '/salesforce-alm/' \
  | filter '/@salesforce/plugin-templates/' \
  | filter '/@salesforce/plugin-generator/' \
  | xargs rm -rf

# JS map files, except the ill-named `lodash.map` (it's a directory and we'll also filter out matches if found for good measure)
find node_modules -name '*.map' -type f \
  | filter 'lodash.map' \
  | xargs rm -f

# In case yarn autoclean is disabled, delete some known windows file path length offenders
find node_modules -name '.nyc_output' -print0 \
  | xargs rm -rf

# Large files shipped with jsforce
find node_modules -name 'build' -type d | (grep "jsforce" || true) \
  | xargs rm -rf

# This breaks compilation. We need to probably do this right before the pack, but then this will
# break compilation the next time compile is ran without doing a yarn install --force
# We don't need types in the production code
# find node_modules -name '*.d.ts' -type f \
#   | xargs rm -f
