#!/usr/bin/env bash

realpath() {
  local result=$(python -c "import os,sys; print os.path.abspath(sys.argv[1])" $1)
  echo $result
}

scripts_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# Removes all caches containing v6 artifacts, reverting to a clean v5 state, if v5 is installed
"$scripts_dir/clean-cache"
rm -rf "$HOE/.local/share/sfdx"
