#!/usr/bin/env bash

set -ex

CHANNEL=latest

# test channel
# CHANNEL=latest-ci-test

CLI_RC_VERSION=${S3_PROMOTE_OVERRIDE_VERSION}
SHA_SHORT=${S3_PROMOTE_OVERRIDE_SHA}

if [ -z "${S3_PROMOTE_OVERRIDE_VERSION}" ]; then
  # get RC version from npm before we promote it to latest!
  CLI_RC_VERSION=$(npm show sfdx-cli --json | jq -r '.["dist-tags"] | .["latest-rc"]')
fi
echo "version to promote: $CLI_RC_VERSION"

if [ -z "${S3_PROMOTE_OVERRIDE_SHA}" ]; then
  # figure out the sha from the release
  SHA=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/salesforcecli/sfdx-cli/tags | jq -cr '.[] | select(.name=='\"v$CLI_RC_VERSION\"') | .commit | .sha')
  echo "found matching sha of ${SHA}"
  SHA_SHORT=$(git rev-parse --short=7 ${SHA})
fi
echo "will use sha of ${SHA_SHORT}"

echo "will run command"
echo "yarn promote --version $CLI_RC_VERSION --sha $SHA_SHORT --channel $CHANNEL --max-age 300 --macos --win"

# promote it
yarn promote --version $CLI_RC_VERSION --sha $SHA_SHORT --channel $CHANNEL --max-age 300 --macos --win
