#!/usr/bin/env bash

set -ex

# get updated channel files from last commit
for channelfile in `git diff --name-only HEAD~1 HEAD | grep "^channels/*"`
do
  read -r _dir channel <<< $(echo $channelfile | tr "/" "\n")
  read -r version sha <<< $(head -n 1 $channelfile | tr "-" "\n")
  echo "Promoting $version-$sha to channel $channel"
  yarn promote --version $version --sha $sha --channel $channel --max-age 300 --macos --win
done
