#!/usr/bin/env bash

set -ex

channel="stable-rc"
read version <<< $(git describe --tags | tr -d "v")
sha=$(git rev-parse --short head)
echo "Promoting $version-$sha to channel $channel"
yarn promote --version $version --sha $sha --channel $channel --max-age 300 --macos --win
