#!/bin/bash

set -ex

get_script_dir () {
  SOURCE="${BASH_SOURCE[0]}"
  # While $SOURCE is a symlink, resolve it
  while [ -h "$SOURCE" ]; do
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$( readlink "$SOURCE" )"
    # If $SOURCE was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  echo "$DIR"
}
DIR=$(get_script_dir)

VERSION=$("$DIR/version")

PLATFORMS=(
  windows-x86
  windows-x64
  darwin-x64
  linux-x86
  linux-x64
  linux-arm
)

if [ $# -ne 1 ]; then
  echo "USAGE: $0 CHANNEL"
  exit 1
fi

ROOT=$(pwd)
CHANNEL=$1
NAME=$(node -p "require('./package.json').name")
S3_BUCKET=$(node -p "require('./package.json')['cli-engine'].s3.bucket")
S3_BASE="s3://$S3_BUCKET/media/salesforce-cli/$NAME"

if [ "$CHANNEL" == "stable" ]; then
  VERSIONED_CACHE_CONTROL=86400   # 1 day
  UNVERSIONED_CACHE_CONTROL=300   # 5 minutes
  LATEST_VERSION_CACHE_CONTROL=60 # 1 minute
else
  VERSIONED_CACHE_CONTROL=0
  UNVERSIONED_CACHE_CONTROL=0
  LATEST_VERSION_CACHE_CONTROL=0
fi

function release {
  remote_path=channels/$CHANNEL
  remote_base="$S3_BASE/$remote_path"
  aws s3 cp --cache-control max-age=$VERSIONED_CACHE_CONTROL "tmp/build/$NAME-v$VERSION-$PLATFORM.tar.xz" "$remote_base/$NAME-v$VERSION-$PLATFORM.tar.xz"
  aws s3 cp --cache-control max-age=$UNVERSIONED_CACHE_CONTROL "$remote_base/$NAME-v$VERSION-$PLATFORM.tar.xz" "$remote_base/$NAME-$PLATFORM.tar.xz"
  aws s3 cp --cache-control max-age=$VERSIONED_CACHE_CONTROL "tmp/build/$NAME-v$VERSION-$PLATFORM.tar.gz" "$remote_base/$NAME-v$VERSION-$PLATFORM.tar.gz"
  aws s3 cp --cache-control max-age=$UNVERSIONED_CACHE_CONTROL "$remote_base/$NAME-v$VERSION-$PLATFORM.tar.gz" "$remote_base/$NAME-$PLATFORM.tar.gz"
  aws s3 cp --cache-control max-age=$LATEST_VERSION_CACHE_CONTROL --content-type application/json "tmp/build/$PLATFORM" "$remote_base/v$VERSION/$PLATFORM"
  aws s3 cp --cache-control max-age=$LATEST_VERSION_CACHE_CONTROL --content-type application/json "tmp/build/$PLATFORM" "$remote_base/$PLATFORM"
}

pids=""
RESULT=0

# install dependencies
YARN_DIR="$ROOT/tmp/build/yarn"
mkdir -p "$YARN_DIR"
cp "$ROOT/package.json" "$YARN_DIR"
cp "$ROOT/yarn.lock" "$YARN_DIR"
cd "$YARN_DIR"
yarn --production --prefer-offline --pure-lockfile
cd "$ROOT"

for PLATFORM in "${PLATFORMS[@]}"; do
  "$DIR/build" "$PLATFORM" "$CHANNEL"
done

for PLATFORM in "${PLATFORMS[@]}"; do
  release &
  pids="$pids $!"
  sleep 3
done

for pid in $pids; do
  wait "$pid" || let "RESULT=1"
done

cat << EOF > tmp/build/version
{
  "channel": "$CHANNEL",
  "version": "$VERSION"
}
EOF

if [ $RESULT -ne 0 ]; then
  exit $RESULT
fi

aws s3 cp --cache-control max-age=$LATEST_VERSION_CACHE_CONTROL --content-type application/json tmp/build/version "$S3_BASE/channels/$CHANNEL/v$VERSION/version"
aws s3 cp --cache-control max-age=$LATEST_VERSION_CACHE_CONTROL --content-type application/json tmp/build/version "$S3_BASE/channels/$CHANNEL/version"
