#!/usr/bin/env bash

# dev and rc should match after promote before RC build
echo "Verifying promote of npm dist tags: dev-rc -> dev"
TAGS=$(npm view sfdx-cli --json | jq -cr '."dist-tags"')
dev=$(echo $TAGS | jq -cr '.dev')
echo $dev
dev_RC=$(echo $TAGS | jq -cr '."dev-rc"')
echo $dev_RC
if [ $dev != $dev_RC ]; then
  echo "dev and dev-rc do not match"
  exit 1
fi

# artifacts and npm should agree on dev
# buildmanifest version for dev matches npm for dev
echo "Verifying promote of aws s3 bucket channels: dev-rc -> dev"
MANIFEST_URL="https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/dev-rc/sfdx-darwin-x64-buildmanifest"
MANIFEST_VERSION=$(curl -s $MANIFEST_URL | jq -cr '.version')
if [ $dev != $MANIFEST_VERSION ]; then
  echo "dev-rc in S3 and dev on npm do not match"
  exit 1
fi

# do an npm install, smoke, verify version, and uninstall
npm install -g sfdx-cli --no-cache
sfdx version
sfdx help
sfdx plugins --core
NPM_CLI_VERSION=$(sfdx version --json | jq -cr '.cliVersion' | sed 's/sfdx-cli\///')
if [ $dev != $NPM_CLI_VERSION ]; then
  echo "npm did not install dev.  dev: $dev.  Npm install $NPM_CLI_VERSION"
  exit 1
fi
npm uninstall -g sfdx-cli

# versions file has dev at the top
VERSIONS_URL="https://developer.salesforce.com/media/salesforce-cli/sfdx/versions/sfdx-linux-x64-tar-xz.json"
VERSION_CONTENT=$(curl -s $VERSIONS_URL | jq -cr)
dev_VERSION=$(echo $VERSION_CONTENT | jq -r 'keys_unsorted[0]')
if [ $dev_VERSION != $dev ]; then
  echo "versions file does not have dev version at the top.  First entry is $dev_VERSION"
  exit 1
fi



# install an older version from installer and then upgrade it to correct version of dev
OLDER_VERSION_URL=$(echo $VERSION_CONTENT | jq 'to_entries[3]' | jq -r '.value')
echo $OLDER_VERSION_URL

# download, untar
curl -s $OLDER_VERSION_URL --output sfdx-linux-x64.tar.xz && mkdir ~/sfdx  && tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1  && rm sfdx-linux-x64.tar.xz
export PATH="~/sfdx/bin:$PATH"

# smoke
sfdx version
sfdx update
sfdx help
sfdx plugins --core
sfdx version

# verify version (will not run until the version it updates from has the --json (v108) option)
# INSTALLED_VERSION=$(sfdx version --json | jq -cr '.cliVersion' | sed 's/sfdx-cli\///')
# if [ $dev != $INSTALLED_VERSION ]; then
#   echo "installer did not install dev.  dev: $dev.  Installer provided $INSTALLED_VERSION"
#   exit 1
# fi

