#!/usr/bin/env bash

# latest and rc should match after promote before RC build
TAGS=$(npm view sfdx-cli --json | jq -cr '."dist-tags"')
LATEST=$(echo $TAGS | jq -cr '.latest')
echo $LATEST
LATEST_RC=$(echo $TAGS | jq -cr '."latest-rc"')
echo $LATEST_RC
if [ LATEST != LATEST_RC ]; then
  echo "latest and latest-rc do not match"
  exit 1
fi

# buildmanifest version for latest matches npm for latest
MANIFEST_URL="https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable-rc/sfdx-darwin-x64-buildmanifest"
MANIFEST_VERSION=$(curl -s $MANIFEST_URL | jq -cr '.version')
if [ LATEST != MANIFEST_VERSION ]; then
  echo "latest in S3 and latest on npm do not match"
  exit 1
fi
