#!/usr/bin/env bash

source ./scripts/_init

set -ex

if [ -x "$(command -v shellcheck)" ]; then
    find scripts -type f -print0 | xargs -0 shellcheck --external-sources
else
    stderr "install shellcheck to lint the scripts"
fi
