#!/usr/bin/env bash

source ./scripts/_init

set -ex

TEST_DIR="${1:-$ROOT_DIR}"

script "test/unit" "$TEST_DIR"
script "test/coverage" "$TEST_DIR"
script "test/smoke"
script "clean/test" "$TEST_DIR"
