#!/usr/bin/env bash

set -ex

source ./scripts/_init

# Make sure we won't include anything unintended in the base dir structure (ignoring node_modules)
find "$BASE_DIR" -path "$BASE_DIR/node_modules" -prune -o -type f -print | while read -r f; do
    set +x
    echo "$f"
    if [[ (
        "$f" != "$BASE_DIR/package.json" &&
        "$f" != "$BASE_DIR/LICENSE" &&
        "$f" != "$BASE_DIR/README.md" &&
        "$f" != "$BASE_DIR/bin/"* &&
        "$f" != "$BASE_DIR/dist/"*".js"
    ) || (
        "$f" == "$BASE_DIR/dist/"*".test.js"
    ) ]]; then
        stderr "Unexpected file found in base build dir! ${f}"
        exit 1
    fi
    set -x
done
