#!/usr/bin/env bash

source ./scripts/_init

set -ex

if [[ ! -d "$TMP_DIR/base" ]]; then
    ./scripts/build/base
fi

function sfdx () {
    node "$TMP_DIR/base/bin/$BIN_NAME.js" "$@"
}

# Enter tmp directory
cd "$(mktemp -d)"

# Disable the background autoupdater when smoke testing
export SFDX_AUTOUPDATE_DISABLE=true

# Run basic smoke tests
sfdx --dev-debug
sfdx version
sfdx help
sfdx plugins --core
sfdx force -h
sfdx force
sfdx force:alias:list
