#!/usr/bin/env bash

source ./scripts/_init

set -ex

TEST_DIR="${1:-$ROOT_DIR}"

cd "$TEST_DIR"

"$ROOT_DIR/node_modules/.bin/nyc" \
    --report lcov \
    --report cobertura \
    "$ROOT_DIR/node_modules/.bin/_mocha" \
    -t 240000 \
    --require source-map-support/register \
    --recursive "$TEST_DIR/dist/**/*.test.js" \
    -R xunit-file
