name: automerge-nightly-pr

on:
  pull_request:
    types: [labeled]

# This job relies on defining required checks in your branch protection settings
# Settings > Branches > 'main' > Require status checks to pass before merging

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release PR for') && endsWith(github.event.pull_request.title, 'nightly')
    steps:
      - name: automerge
        # https://github.com/pascalgn/automerge-action
        uses: 'pascalgn/automerge-action@eb68b061739cb9d81564f8e812d0b3c45f0fb09a'
        env:
          GITHUB_TOKEN: '${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}'
          MERGE_LABELS: 'nightly-automerge'
          MERGE_COMMIT_MESSAGE: 'pull-request-title' # Use the PR title as the commit message
          MERGE_FILTER_AUTHOR: 'svc-cli-bot' # Only automerge PRs from this author
          MERGE_REQUIRED_APPROVALS: '0'
          MERGE_DELETE_BRANCH: 'true'
          MERGE_FORKS: 'false'
          MERGE_ERROR_FAIL: 'true' # Exit 1 for this action if merge fails
          MERGE_RETRIES: '10' # Wait for checks to complete
          MERGE_RETRY_SLEEP: '180000' # 3 minutes (30 minutes total)
