name: automerge-dependabot
on:
  workflow_dispatch:
  schedule:
    - cron: '18 1,4,7,10 * * *'

jobs:
  automerge:
    uses: salesforcecli/github-workflows/.github/workflows/automerge.yml@main
    with:
      mergeMethod: squash
    secrets: inherit
