name: just-nut
on:
  workflow_dispatch:
    inputs:
      channel-or-version:
        description: Version or channel of the CLI to test against (nightly, latest-rc, 7.112.1)
        type: string
        default: 'latest-rc' # TODO: Update this to 'nightly'
      repository:
        description: 'The repo that will be cloned (format: owner/repo).  This contains the NUTs you want to run.  Ex: salesforcecli/plugin-user'
        type: string
        required: true
      command:
        required: false
        type: string
        default: yarn test:nuts
        description: 'command to execute (ex: yarn test:nuts)'
      os:
        required: false
        description: 'runs-on property, ex: ubuntu-latest, windows-latest'
        type: string
        default: 'ubuntu-latest'
  workflow_call:
    inputs:
      channel-or-version:
        description: Version or channel of the CLI to test against (nightly, latest-rc, 7.112.1)
        default: 'latest-rc' # TODO: Update this to 'nightly'
        type: string
      repository:
        description: 'The repo that will be cloned (format: owner/repo).  This contains the NUTs you want to run.  Ex: salesforcecli/plugin-user'
        type: string
        required: true
      command:
        required: false
        type: string
        default: yarn test:nuts
        description: 'command to execute (ex: yarn test:nuts)'
      os:
        required: false
        description: 'runs-on property, ex: ubuntu-latest, windows-latest'
        type: string
        default: 'ubuntu-latest'

jobs:
  just-nut:
    name: ${{inputs.repository}}
    runs-on: ${{inputs.os}}
    env:
      TESTKIT_EXECUTABLE_PATH: sfdx
      TESTKIT_AUTH_URL: ${{ secrets.TESTKIT_AUTH_URL}}
      TESTKIT_HUB_USERNAME: ${{ secrets.TESTKIT_HUB_USERNAME}}
      TESTKIT_JWT_CLIENT_ID: ${{ secrets.TESTKIT_JWT_CLIENT_ID}}
      TESTKIT_JWT_KEY: ${{ secrets.TESTKIT_JWT_KEY}}
      TESTKIT_HUB_INSTANCE: ${{ secrets.TESTKIT_HUB_INSTANCE}}
      TESTKIT_SETUP_RETRIES: 2

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{inputs.repository}}
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
          path: .
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
        # NOTE: We are just using latest-rc of `sf` since we cannot guaranteed channels (and definitely versions) will be the same
      - run: npm install -g sfdx-cli@{{ inputs.channel-or-version }} @salesforce/cli@latest-rc --omit=dev
      - run: yarn install
      - name: NUTs attempt 1
        continue-on-error: true
        id: nut1
        run: ${{ inputs.command }}
      - name: NUTs attempt 2
        continue-on-error: true
        id: nut2
        if: steps.nut1.outcome == 'failure'
        run: |
          echo "::notice title=NUT Retry::NUT '${{inputs.command}}' failed and was retried."
          ${{ inputs.command }}
      - name: NUTs attempt 3
        if: steps.nut2.outcome == 'failure'
        run: |
          echo "::warning title=NUT Retry 2::NUT '${{inputs.command}}' failed twice and was retried."
          ${{ inputs.command }}
