name: pr for rc

on:
  workflow_dispatch:
    inputs:
      patch:
        type: boolean
        required: false
        default: false
        description: increment the patch instead of the minor version
      only:
        type: string
        required: false
        description: comma-separated list, no spaces, of dependencies that you want to bump.
  workflow_run:
    workflows: [promote-rc-to-latest]
    types:
      - completed

jobs:
  rcPR:
    if: ${{ !github.event.workflow_run || github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      SFDX_HIDE_RELEASE_NOTES: true
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm install -g @salesforce/plugin-release-management --omit=dev
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
      # latest-rcs will be built from main
      - run: sf-release cli:release:build --start-from-github-ref main
        if: ${{ !inputs.patch && !inputs.only }}
      - run: sf-release cli:release:build --start-from-github-ref main --only ${{inputs.only}}
        if: ${{ !inputs.patch && inputs.only }}
        # patches to latest-rc will be built from the version looked up from npm for latest-rc
      - run: sf-release cli:release:build --start-from-npm-dist-tag latest-rc --patch
        if: ${{ inputs.patch && !inputs.only }}
      - run: sf-release cli:release:build --start-from-npm-dist-tag latest-rc --patch --only ${{inputs.only}}
        if: ${{ inputs.patch && inputs.only }}
