name: promote-rc-to-latest

on:
  workflow_dispatch:
  schedule:
    # Thursdays 9a central
    - cron: '0 14 * * 4'

jobs:
  # what is the RC version, numerically?
  getVersion:
    outputs:
      version: ${{ steps.version-info.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: salesforcecli/github-workflows/.github/actions/versionInfo@re/rename-mac-pkg
        id: version-info
        with:
          version: dev-rc

  promote:
    uses: ./.github/workflows/promote.yml
    needs: getVersion
    secrets: inherit
    with:
      version: ${{needs.getVersion.outputs.version}}
      tag: dev
      channel: dev
      useCTC: true

  promote-verify:
    runs-on: ubuntu-latest
    needs: [promote]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: ./scripts/verify-promote
      # TODO: Comment these back in before merging into main
      # - run: npm install -g @salesforce/plugin-release-management --omit=dev
      # - run: sf-release cli:versions:inspect -c dev -l archive

  announce-promotion-to-slack:
    # Only runs on main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [getVersion, promote-verify]
    steps:
      - name: Announce promotion
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_CLI_CHANNEL_SLACK_INCOMING_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: `sfdx-cli` version `${{ needs.getVersion.outputs.version }}` has been promoted to latest :rocket:\nRun `sfdx whatsnew -v latest` to see what's new"
                }
              }]
            }
