name: promote-nightly-to-rc

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - promote-rc-to-latest
    types:
      - completed

jobs:
  promote:
    uses: ./.github/workflows/promote.yml
    secrets: inherit
    with:
      old-channel: nightly
      new-channel: latest-rc

  announce-promotion-to-slack:
    needs: promote
    runs-on: ubuntu-latest
    steps:
      - name: Get nightly version
        id: nightly-version
        run: |
          VERSION=$(npm view sfdx-cli@nightly --json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Announce promotion
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_CLI_CHANNEL_SLACK_INCOMING_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":owl3: `sfdx-cli` version `${{ steps.nightly-version.outputs.version }}` has been promoted from `nightly` to `latest-rc` :owl3:\nRun `sfdx whatsnew -v latest-rc` to see what's new"
                }
              }]
            }
