name: promote-rc-to-latest

on:
  workflow_dispatch:
  schedule:
    # Thursdays 1pm central
    - cron: '0 18 * * 4'

jobs:
  promote:
    uses: ./.github/workflows/promote.yml
    secrets: inherit
    with:
      old-channel: latest-rc
      new-channel: latest
      use-ctc: true

  promote-verify:
    runs-on: ubuntu-latest
    needs: [promote]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: ./scripts/verify-promote latest-rc latest
      - name: Install plugin-release-management
        run: npm install -g @salesforce/plugin-release-management --omit=dev
      - name: Verify promoted versions
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd
        with:
          max_attempts: 5
          retry_wait_seconds: 120
          command: sf-release cli:versions:inspect -c stable -l archive
          retry_on: error
          timeout_minutes: 60

  announce-promotion-to-slack:
    runs-on: ubuntu-latest
    needs: [promote-verify]
    steps:
      - name: Get latest-rc version
        id: latest-rc-version
        run: |
          VERSION=$(npm view sfdx-cli@latest-rc --json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Announce promotion
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_CLI_CHANNEL_SLACK_INCOMING_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: `sfdx-cli` version `${{ steps.latest-rc-version.outputs.version }}` has been promoted from `latest-rc` to `latest` :rocket:\nRun `sfdx whatsnew -v latest` to see what's new"
                }
              }]
            }
