name: promote-nightly-to-rc

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - promote-rc-to-latest
    types:
      - completed

jobs:
  promote:
    # Only run on 'workflow_dispatch' or if the 'workflow_run' was successful
    if: ${{ github.event.workflow_dispatch || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/promote.yml
    secrets: inherit
    with:
      old-channel: nightly
      new-channel: latest-rc

  promote-verify:
    runs-on: ubuntu-latest
    needs: [promote]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: ./scripts/verify-promote nightly latest-rc
      - run: npm install -g @salesforce/plugin-release-management --omit=dev
      - run: |
          ATTEMPT=1
          MAX=5
          DELAY=120 # two minutes

          # Retry several times because the S3 cache can cause failures
          # Command: sf-release cli:versions:inspect -c stable-rc -l archive

          while true; do
              sf-release cli:versions:inspect -c stable-rc -l archive && break || {
                  if [[ $ATTEMPT -lt $MAX ]]; then
                      ((ATTEMPT++))
                      echo "Promote verify failed - trying again ($ATTEMPT/$MAX)"
                      sleep $DELAY;
                  else
                      "Exiting after $ATTEMPT failed attempts"
                      exit 1
                  fi
              }
          done

  announce-promotion-to-slack:
    needs: [promote-verify]
    runs-on: ubuntu-latest
    steps:
      - name: Get nightly version
        id: nightly-version
        run: |
          VERSION=$(npm view sfdx-cli@nightly --json | jq -r '.version')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Announce promotion
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.PLATFORM_CLI_CHANNEL_SLACK_INCOMING_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":owl3: `sfdx-cli` version `${{ steps.nightly-version.outputs.version }}` has been promoted from `nightly` to `latest-rc` :owl3:\nRun `sfdx whatsnew -v latest-rc` to see what's new"
                }
              }]
            }
