name: promote-rc-to-latest

on:
  workflow_dispatch:
  schedule:
    # Thursdays 9a central
    - cron: '0 14 * * 4'

jobs:
  # what is the RC version, numerically?
  getVersion:
    outputs:
      version: ${{ steps.version-info.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: salesforcecli/github-workflows/.github/actions/versionInfo@main
        id: version-info
        with:
          version: latest-rc

  promote:
    uses: ./.github/workflows/promote.yml
    needs: getVersion
    secrets: inherit
    with:
      version: ${{needs.getVersion.outputs.version}}
      tag: latest
      channel: stable
      useCTC: true

  promote-verify:
    runs-on: ubuntu-latest
    needs: [promote]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
      - run: ./scripts/verify-promote
      - run: npm install -g sfdx-cli @salesforce/plugin-release-management --omit=dev
      - run: sf-release cli:versions:inspect -c stable -l archive

  announce:
    runs-on: ubuntu-latest
    needs: [getVersion, promote-verify]

    steps:
      - name: Announce promotion
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          # TODO: post these to the normal platform-cli channel after testing
          SLACK_WEBHOOK_URL: ${{ secrets.CLI_ALERTS_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "sfdx-cli version ${{ needs.getVersion.outputs.version }} has been promoted to latest :tada2:\nRun `sfdx whatsnew -v latest` to see what's new"
                }
              }]
            }
