name: promote

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: full npm version number, like 7.150.2
        required: true
      tag:
        type: string
        required: false
        description: tag to use for docker/npm, like latest or latest-rc
        default: latest
      channel:
        type: string
        required: true
        default: dev
        description: channel to promote the matching tarball to (example dev, dev-rc )
      useCTC:
        type: boolean
        required: false
        description: this promotion should only run if no release moratorium is in place

jobs:
  ctc-open:
    if: inputs.useCTC
    uses: salesforcecli/github-workflows/.github/workflows/ctcOpen.yml@re/rename-mac-pkg
    secrets: inherit

  docker-promote:
    needs: [ctc-open]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker pull salesforce/salesforcedx:${{ inputs.version }}-slim
          docker tag salesforce/salesforcedx:${{ inputs.version }}-slim salesforce/salesforcedx:${{ inputs.tag }}-slim
          docker push salesforce/salesforcedx:${{ inputs.tag }}-slim

          docker pull salesforce/salesforcedx:${{ inputs.version }}-full
          docker tag salesforce/salesforcedx:${{ inputs.version }}-full salesforce/salesforcedx:${{ inputs.tag }}-full
          docker push salesforce/salesforcedx:${{ inputs.tag }}-full

  npm-promote:
    needs: [ctc-open]
    runs-on:
      ubuntu-latest
      # if you try to use yarn here, it will attempt to use the wrong registry and throw 401s
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm dist-tag add sfdx-cli@${{ inputs.version }} ${{ inputs.tag }}

  channel-promote:
    needs: [ctc-open]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      # to get the SHA
      - uses: salesforcecli/github-workflows/.github/actions/versionInfo@re/rename-mac-pkg
        id: version-info
        with:
          version: ${{ inputs.version }}
          npmPackage: sfdx-cli
      - run: yarn promote --version ${{ steps.version-info.outputs.version }} --sha ${{ steps.version-info.outputs.sha }} --channel ${{ inputs.channel }} --max-age 300 --macos --win --indexes --xz
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  rename-mac-pkg:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli:2.8.6
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [channel-promote]
    steps:
      - run: aws s3 cp s3://dfc-data-production/media/salesforce-cli/sfdx/channels/${{ inputs.channel }}/sfdx-x64.pkg ./sfdx.pkg
      - run: aws s3 cp ./sfdx.pkg s3://dfc-data-production/media/salesforce-cli/sfdx/channels/${{ inputs.channel }}/

  ctcCloseSuccess:
    needs: [ctc-open, npm-promote, docker-promote, channel-promote, rename-mac-pkg]
    if: needs.ctc-open.result == 'success' && needs.ctc-open.outputs.changeCaseId && needs.npm-promote.result == 'success' && needs.docker-promote.result == 'success' && needs.channel-promote.result == 'success' && needs.rename-mac-pkg.result == 'success'
    uses: salesforcecli/github-workflows/.github/workflows/ctcClose.yml@re/rename-mac-pkg
    secrets: inherit
    with:
      changeCaseId: ${{needs.ctc-open.outputs.changeCaseId}}

  ctcCloseFail:
    needs: [ctc-open, npm-promote, docker-promote, channel-promote, rename-mac-pkg]
    if: always() && needs.ctc-open.outputs.changeCaseId && (needs.ctc-open.result != 'success' || needs.npm-promote.result != 'success' || needs.docker-promote.result != 'success' || needs.channel-promote.result != 'success' || needs.rename-mac-pkg.result != 'success')
    uses: salesforcecli/github-workflows/.github/workflows/ctcClose.yml@re/rename-mac-pkg
    secrets: inherit
    with:
      changeCaseId: ${{ needs.ctc-open.outputs.changeCaseId }}
      status: Not Implemented
