name: qa-just-nuts

on:
  push:
    branches: [sm/gha]

jobs:
  basic:
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        url:
          # - https://github.com/salesforcecli/plugin-alias
          - https://github.com/salesforcecli/plugin-auth
          # - https://github.com/salesforcecli/plugin-community
          # omitted while nuts are too flaky on bulk commands
          # - https://github.com/salesforcecli/plugin-data
          # - https://github.com/salesforcecli/plugin-limits
          # - https://github.com/salesforcecli/plugin-org
          # - https://github.com/salesforcecli/plugin-schema
          # - https://github.com/salesforcecli/plugin-signups
          # - https://github.com/salesforcecli/plugin-user

          # private repos
          - https://github.com/salesforcecli/toolbelt
          - https://github.com/salesforcecli/plugin-custom-metadata
    uses: ./.github/workflows/justNut.yml
    with:
      externalProjectGitUrl: ${{matrix.url}}
      os: ${{matrix.os}}
    secrets: inherit
