name: RC
on:
  release:
    types: [published]

jobs:
  npm-release:
    uses: salesforcecli/github-workflows/.github/workflows/npmPublish.yml@main
    secrets: inherit
    with:
      tag: latest-rc
      githubTag: ${{ github.event.release.tag_name }}

  pack-verify-upload-tarballs:
    needs: [npm-release]
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
    with:
      upload: true
      cli: sfdx
      version: ${{ github.event.release.tag_name }}
      channel: dev-rc
    secrets: inherit

  archives-verify:
    runs-on: ubuntu-latest
    needs: [pack-verify-upload-tarballs]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm
      - run: npm install -g @salesforce/plugin-release-management --omit=dev
      - run: sf-release cli:versions:inspect -c dev-rc -l archive

  pack-upload-mac:
    needs: [pack-verify-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadMac.yml@main
    with:
      cli: sfdx
      version: ${{ github.event.release.tag_name }}
      channel: dev-rc
    secrets: inherit

  pack-upload-win:
    needs: [pack-verify-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadWindows.yml@main
    with:
      cli: sfdx
      version: ${{ github.event.release.tag_name }}
      channel: dev-rc
    secrets: inherit

  docker-slim:
    needs: [pack-verify-upload-tarballs]
    uses: ./.github/workflows/dockerBuildSlim.yml
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit

  docker-full:
    needs: [npm-release]
    uses: ./.github/workflows/dockerBuildFull.yml
    with:
      version: ${{ github.event.release.tag_name }}
    secrets: inherit

  Post-RC-to-Slack:
    runs-on: ubuntu-latest
    needs: [pack-verify-upload-tarballs, npm-release, docker-slim, docker-full, pack-upload-win, pack-upload-mac]
    steps:
      - name: Announce RC Workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RC_ANNOUNCEMENT_WORKFLOW_WEBHOOK }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "cli": "sfdx",
              "npm-package": "sfdx-cli",
              "version": "${{ github.event.release.tag_name }}"
            }
