name: RC
on:
  release:
    types: [published]

jobs:
  npm-release:
    uses: salesforcecli/github-workflows/.github/workflows/githubRelease.yml@main
    secrets: inherit

  test-pack-upload-tarballs:
    needs: [npm-release]
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
    with:
      upload: true
      cli: sfdx
      version: ${{ format(github.event.release.tag_name, 'v', '') }}
      channel: stable-rc
    secrets: inherit

  pack-upload-mac:
    needs: [test-pack-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadMac.yml@main
    with:
      cli: sfdx
      version: ${{ format(github.event.release.tag_name, 'v', '') }}
      channel: stable-rc
    secrets: inherit

  pack-upload-win:
    needs: [test-pack-upload-tarballs]
    uses: salesforcecli/github-workflows/.github/workflows/packUploadWindows.yml@main
    with:
      cli: sfdx
      version: ${{ format(github.event.release.tag_name, 'v', '') }}
      channel: stable-rc
    secrets: inherit

  docker-slim:
    needs: [test-pack-upload-tarballs]
    uses: ./.github/workflows/dockerBuildSlim.yml
    with:
      version: ${{ format(github.event.release.tag_name, 'v', '') }}
    secrets: inherit

  docker-full:
    needs: [npm-release]
    uses: ./.github/workflows/dockerBuildFull.yml
    with:
      version: ${{ format(github.event.release.tag_name, 'v', '') }}
    secrets: inherit

  Post-RC-to-Slack:
    if: always() && success()
    runs-on: ubuntu-latest
    needs: [test-pack-upload-tarballs, npm-release, docker-slim, docker-full, pack-upload-win, pack-upload-mac]
    steps:
      - name: Announce RC Workflow
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RC_ANNOUNCEMENT_WORKFLOW_WEBHOOK }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "cli": "sfdx",
              "npm-package": "sfdx-cli",
              "version": "${{ format(github.event.release.tag_name, 'v', '') }}"
            }

  failure-notify:
    if: always() && (cancelled() ||  failure())
    runs-on: ubuntu-latest
    steps:
      - name: Announce Failure
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CLI_ALERTS_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "RC fail",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
