name: DEBUG windows pack and sign
on:
  push:
    branches: [sm/oclif-win-signing-debug]

jobs:
  pack-upload-win:
    uses: salesforcecli/github-workflows/.github/workflows/packUploadWindows.yml@main
    with:
      cli: sfdx
      version: 7.180.0
      channel: stable-rc
    secrets: inherit
