name: update-docker-node-version

on:
  workflow_dispatch:
  schedule:
    # Thursday 7a central
    - cron: '0 12 * * 4'

jobs:
  update-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: node ./dockerfiles/update-docker-node-version.js
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main
      # Push changes if 'git status' is not empty
      - run: |
          if [[ -n $(git status --short) ]]; then
            git add dockerfiles/Dockerfile_full
            git commit -m "chore: update node in dockerfile_full" --no-verify
            git push --no-verify
          else
            echo "Already up to date"
          fi
