# test push
name: pr-validation

on:
  pull_request:
    types: [opened, reopened, edited]
    # only applies to PRs that want to merge to re/update-oclif-v3
    branches: [re/update-oclif-v3]

jobs:
  pr-validation:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@re/rename-mac-pkg
