# test push
name: pr-validation

on:
  pull_request:
    types: [opened, reopened, edited]
    # only applies to PRs that intent to be released to the public
    branches:
      - main
      - patch/*

jobs:
  pr-validation:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
