name: Test salesforcecli-windows runner
on:
  push:
    branches:
      - re/salesforce-windows-runner

jobs:
  windows-unit-tests:
    strategy:
      matrix:
        node_version: [lts/*]
      fail-fast: true
    runs-on: salesforcecli-windows
    steps:
      - uses: actions/checkout@v3
      - uses: salesforcecli/github-workflows/.github/actions/windowsCachePerf@main
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install  --network-timeout 600000
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn build
      - run: yarn test